  Start
    List
      Script
        List
          CommandBlock
            List
              ValueExp"a"
              ValueExp"b"
              ValueExp"s"
          CommandBlock
            List
              ValueExp"a"
              ValueExp"b"
              ValueExp"s"
